fragment AboutParts on About {
  __typename
  header {
    __typename
    image
    label1
    label2
    label3
    label4
    label5
    label6
    label7
    button
  }
  heroText {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerContent
  }
  displayinsights {
    __typename
    Headingone
    Headingtwo
    insight
  }
}

fragment BlogParts on Blog {
  __typename
  header {
    __typename
    image
    label1
    label2
    label3
    label4
    label5
    label6
    label7
    button
  }
  heroText {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerContent
    bannerButtonText1
    bannerButtonText2
    bannerImage
  }
  horizhover {
    __typename
    title
    content
    image1
    title1
    content1
    image2
    title2
    content2
  }
  sectionThree {
    __typename
    digital
    digitalspan
    digitalcontent
    title1
    content1
    title2
    content2
    image
  }
  displayinsights {
    __typename
    Headingone
    Headingtwo
    insight
  }
}

fragment RealtimeParts on Realtime {
  __typename
  header {
    __typename
    image
    label1
    label2
    label3
    label4
    label5
    label6
    label7
    button
  }
  heroText {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerContent
    bannerButtonText1
    bannerButtonText2
    bannerImage
  }
  horizhover {
    __typename
    title
    content
    image1
    title1
    content1
    image2
    title2
    content2
  }
  sectionThree {
    __typename
    digital
    digitalspan
    digitalcontent
    title1
    content1
    title2
    content2
    image
  }
  displayinsights {
    __typename
    Headingone
    Headingtwo
    insight
  }
  rgs {
    __typename
    readyheading
    spanheading
    readycontent
    bannerButtonText1
    bannerButtonText2
  }
  rgstwo {
    __typename
    readyheadingtwo
    readycontenttwo
    bannerButtonText3
    readytwoimage
  }
  rgsthree {
    __typename
    readyheadingthree
    readycontentthree
    apibuttons
    readythreeimage
  }
  faq {
    __typename
    faqheading
    questions {
      __typename
      question
      answer
      ctatext
      ctalink
    }
  }
}

fragment PageParts on Page {
  __typename
  banner {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerSubTitle
    bannerButtonText
  }
  sectionOne {
    __typename
    sectionOneText
    sectionOneImage
  }
  sectionTwo {
    __typename
    TableHead1
    TableHead2
    TableHead3
    TableHead4
    TableBody1
    TableBody2
    TableBody3
    TableBody4
    TableImage1
    TableImage2
    TableImage3
    TableImage4
    TableImageAlt
  }
  sectionThreeText {
    __typename
    Heading
    Content
    Button
  }
  sectionFourText {
    __typename
    HeadingI
    HeadingII
    HeadingIII
    ImageTopText
    Image
    HoverList {
      __typename
      Heading1
      Content1
      Heading2
      Content2
      Heading3
      Content3
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  body
}
