fragment BlogParts on Blog {
  __typename
  heroText {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerContent
    bannerButtonText1
    bannerButtonText2
    bannerImage
  }
  sectionTwo {
    __typename
    title
    titlecontent
    titlecontentimage
    title2
    titlecontent2
    titlecontentimage3
    title3
    titlecontent3
  }
  sectionThree {
    __typename
    digital
    digitalspan
    digitalcontent
  }
  displayinsights {
    __typename
    Headingone
    Headingtwo
    insight
  }
  rgs {
    __typename
    readyheading
    spanheading
    readycontent
    bannerButtonText1
    bannerButtonText2
  }
  rgstwo {
    __typename
    readyheadingtwo
    readycontenttwo
    bannerButtonText3
    readytwoimage
  }
  rgsthree {
    __typename
    readyheadingthree
    readycontentthree
    apibuttons
    readythreeimage
  }
  faq {
    __typename
    faqheading
    questions {
      __typename
      question
      answer
      ctatext
      ctalink
    }
  }
}

fragment PageParts on Page {
  __typename
  banner {
    __typename
    bannerTitle
    bannerSpanTitle
    bannerSubTitle
    bannerButtonText
  }
  sectionOne {
    __typename
    sectionOneText
    sectionOneImage
  }
  sectionTwo {
    __typename
    TableHead1
    TableHead2
    TableHead3
    TableHead4
    TableBody1
    TableBody2
    TableBody3
    TableBody4
    TableImage1
    TableImage2
    TableImage3
    TableImage4
    TableImageAlt
  }
  sectionThreeText {
    __typename
    Heading
    Content
    Button
  }
  sectionFourText {
    __typename
    HeadingI
    HeadingII
    HeadingIII
    ImageTopText
    Image
    HoverList {
      __typename
      Heading1
      Content1
      Heading2
      Content2
      Heading3
      Content3
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  body
}
