name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: |
          # Production
          $(if [ ${{ github.ref }} == 'refs/heads/main' ]; then echo "build"; fi)
          # Development
          $(if [ ${{ github.ref }} == 'refs/heads/dev' ]; then echo "build-dev"; fi)
        destination_dir: |
          $(if [ ${{ github.ref }} == 'refs/heads/main' ]; then echo "/production"; fi)
          $(if [ ${{ github.ref }} == 'refs/heads/dev' ]; then echo "/development"; fi)
